### PR TITLE
Added introduction

### PR DESCRIPTION
**Pull request by mattytrentini**
Added an introduction; effectively an overview of the workshop structure.

### CODE REVIEW

**Comment by HowManyOliversAreThere** [comment]
Intro looks good, some minor grammar changes made.

In line with the name of the branch, is migration of `infrared.rst` and `ambient_light.rst` to an `other.rst` (or similar) planned to happen in this branch / PR?

**Comment by mattytrentini** [comment]
Was undecided but I'll add it to this branch; give me a little longer!

**Comment by HowManyOliversAreThere** [comment]
@mattytrentini missing `other.rst` from your commit?

**Comment by HowManyOliversAreThere** [comment]
Looks good now, merging!

**Pull request merged**
